# Generated by Django 3.1.4 on 2021-02-10 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Название студии')),
                ('director', models.CharField(max_length=50, verbose_name='Директор студии')),
                ('date_sign', models.DateField(verbose_name='Дата основания')),
            ],
            options={
                'verbose_name': 'Киностудия',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название фильма')),
                ('actors', models.TextField(verbose_name='Актеры')),
                ('plot', models.TextField(verbose_name='Сюжет')),
                ('date', models.DateField(verbose_name='Дата выхода в прокат')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Возраст анкетируемого')),
                ('country', models.CharField(max_length=50, verbose_name='Страна проживания')),
                ('city', models.CharField(max_length=50, verbose_name='Город проживания')),
                ('level_education', models.CharField(max_length=50, verbose_name='Уровень образования')),
                ('hobby', models.TextField(verbose_name='Хобби анкетируемого')),
                ('favorite_movies', models.TextField(verbose_name='Любимые фильмы')),
                ('desired_of_activity', models.TextField(verbose_name='Желаемый вид деятельности в студии')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='worker_contact', serialize=False, to='cineMania.contacts')),
                ('job_position', models.CharField(max_length=30, verbose_name='Должность')),
                ('experience', models.IntegerField(verbose_name='Опыт работы')),
                ('yearEnd_study', models.DateField(verbose_name='Дата окончания университета')),
                ('degree', models.CharField(max_length=30, verbose_name='Степень')),
                ('description', models.TextField(verbose_name='Комментарий о себе')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта, для обратной связи с пользователем')),
                ('country', models.CharField(max_length=50, verbose_name='Страна проживания')),
                ('question', models.TextField(verbose_name='Вопрос к руководству киностудии')),
                ('cinemaStudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineMania.cinemastudio')),
            ],
            options={
                'verbose_name': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='CastingParticipants',
            fields=[
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='casting_quest', serialize=False, to='cineMania.questionnaire')),
                ('cinemaStudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineMania.cinemastudio')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='casting_contact', to='cineMania.contacts')),
            ],
            options={
                'verbose_name': 'Участник кастинга',
                'verbose_name_plural': 'Участники кастинга',
            },
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='related_contact', serialize=False, to='cineMania.contacts')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('sex', models.CharField(max_length=1, verbose_name='Пол')),
                ('count_films', models.IntegerField(verbose_name='Фильмография')),
                ('film', models.ManyToManyField(related_name='related_actors', to='cineMania.Film')),
            ],
            options={
                'verbose_name': 'Актера',
                'verbose_name_plural': 'Актеры',
            },
        ),
    ]
